CREATE DATABASE QL_Duan_NguyenVanDuy
GO	

USE QL_Duan_NguyenVanDuy
GO

CREATE TABLE dbo.NHANVIEN (
	MANV VARCHAR(10) NOT NULL,
	HOTENNV NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	MACHUCVU VARCHAR(5) NOT NULL,
	
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (
		MANV ASC
	)
)

CREATE TABLE dbo.DUAN (
	MADUAN VARCHAR(10) NOT NULL,
	TENDUAN NVARCHAR(50) NOT NULL,
	KINHPHI INT NOT NULL,
	TGBD DATETIME NOT NULL,
	TGKT DATETIME NOT NULL,
	
	CONSTRAINT PK_DUAN PRIMARY KEY (
		MADUAN ASC
	)
)

CREATE TABLE dbo.CHUCVU (
	MACHUCVU VARCHAR(5) NOT NULL,
	TENCHUCVU NVARCHAR(50) NOT NULL,
	LUONGCB INT NOT NULL,
	
	CONSTRAINT PK_CHUCVU PRIMARY KEY (
		MACHUCVU ASC
	)
)

CREATE TABLE dbo.PHANCONG (
	MADUAN VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	SONGAYCONG INT NOT NULL,
	
	CONSTRAINT PK_PHANCONG PRIMARY KEY (
		MADUAN ASC,
		MANV ASC
	)
)




ALTER TABLE dbo.NHANVIEN ADD CONSTRAINT FK_NHANHVIEN_CHUCVU FOREIGN KEY(MACHUCVU)
REFERENCES dbo.CHUCVU (MACHUCVU)
GO

ALTER TABLE dbo.PHANCONG ADD CONSTRAINT FK_PHANCONG_DUAN FOREIGN KEY (MADUAN)
REFERENCES dbo.DUAN (MADUAN)
GO

ALTER TABLE dbo.PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV)
REFERENCES dbo.NHANVIEN (MANV)
GO	




INSERT INTO dbo.NHANVIEN
(
    MANV,
    HOTENNV,
    NGAYSINH,
    GIOITINH,
    MACHUCVU
)
VALUES
(   'GV.0001',        -- MANV - varchar(10)
    N'Lưu Thành Long',       -- HOTENNV - nvarchar(50)
    '19850110', -- NGAYSINH - datetime
    N'Nam',       -- GIOITINH - nvarchar(3)
    'TV'         -- MACHUCVU - varchar(5)
    )
GO

INSERT INTO dbo.DUAN
(
    MADUAN,
    TENDUAN,
    KINHPHI,
    TGBD,
    TGKT
)
VALUES
(   'CB.001',        -- MADUAN - varchar(10)
    N'Quốc lộ 1A - Ninh Bình',       -- TENDUAN - nvarchar(50)
    50000,         -- KINHPHI - int
    '20150101', -- TGBD - datetime
    '20180101'  -- TGKT - datetime
    )
GO


INSERT INTO dbo.CHUCVU
(
    MACHUCVU,
    TENCHUCVU,
    LUONGCB
)
VALUES
(   'TV',  -- MACHUCVU - varchar(5)
    N'Thành viên', -- TENCHUCVU - nvarchar(50)
    450    -- LUONGCB - int
    )  
GO

INSERT INTO dbo.PHANCONG
(
    MADUAN,
    MANV,
    SONGAYCONG
)
VALUES
(   'CB.001', -- MADUAN - varchar(10)
    'GV.0001', -- MANV - varchar(10)
    150   -- SONGAYCONG - int
    )
GO


 


 -- b.1
SELECT 
	DUAN.MADUAN,
	DUAN.TENDUAN,
	DATEDIFF(month, DUAN.TGBD, DUAN.TGKT) AS SoThangThucHien,
	COUNT(PHANCONG.MANV) AS SoNhanVien,
	SUM(PHANCONG.SONGAYCONG) AS TongSoNgayThucHien
FROM 
	DUAN
	INNER JOIN PHANCONG ON DUAN.MADUAN = PHANCONG.MADUAN
WHERE 
	YEAR(DUAN.TGBD) = 2022
	AND YEAR(DUAN.TGKT) = 2022
GROUP BY 
	DUAN.MADUAN,
	DUAN.TENDUAN,
	DATEDIFF(month, DUAN.TGBD, DUAN.TGKT)
	

-- b.3
SELECT TOP(1)
	dbo.DUAN.MADUAN,
	TENDUAN
FROM 
	dbo.DUAN,
	dbo.PHANCONG
WHERE
	dbo.DUAN.MADUAN = dbo.PHANCONG.MADUAN
ORDER BY
	DATEDIFF(DAY, DUAN.TGBD, DUAN.TGKT) ASC,
	SONGAYCONG DESC



-- b.5
SELECT TOP(1)
	dbo.DUAN.MADUAN,
	dbo.DUAN.TENDUAN,
	dbo.DUAN.TGBD,
	dbo.DUAN.TGKT
FROM
	dbo.DUAN,
	dbo.PHANCONG
WHERE
	dbo.DUAN.MADUAN = dbo.PHANCONG.MADUAN
GROUP BY
	dbo.DUAN.MADUAN,
	dbo.DUAN.TENDUAN,
	dbo.DUAN.TGBD,
	dbo.DUAN.TGKT
ORDER BY
	COUNT(dbo.PHANCONG.MANV) DESC



-- b.4
SELECT 
	dbo.NHANVIEN.MANV,
	dbo.NHANVIEN.HOTENNV,
	dbo.NHANVIEN.NGAYSINH,
	dbo.NHANVIEN.GIOITINH
FROM
	dbo.NHANVIEN
WHERE
	dbo.NHANVIEN.MANV NOT IN (
		SELECT
			dbo.PHANCONG.MANV
		FROM 
			dbo.DUAN,
			dbo.PHANCONG
		WHERE
			dbo.DUAN.MADUAN = dbo.PHANCONG.MADUAN
			AND (YEAR(TGBD) = 2022 OR YEAR(TGKT) = 2022)
		)


-- b.2
SELECT 
	dbo.NHANVIEN.MANV,
	dbo.NHANVIEN.HOTENNV,
	dbo.CHUCVU.TENCHUCVU,
	(SUM(SONGAYCONG) * dbo.CHUCVU.LUONGCB)
FROM
	dbo.NHANVIEN,
	dbo.CHUCVU,
	dbo.PHANCONG
WHERE
	dbo.NHANVIEN.MACHUCVU = dbo.CHUCVU.MACHUCVU
	AND dbo.NHANVIEN.MANV = dbo.PHANCONG.MANV
GROUP BY
	dbo.NHANVIEN.MANV,
	dbo.NHANVIEN.HOTENNV,
	dbo.CHUCVU.TENCHUCVU,
	dbo.CHUCVU.LUONGCB


-- b.6
SELECT
	dbo.NHANVIEN.MANV,
	dbo.NHANVIEN.HOTENNV,
	dbo.NHANVIEN.GIOITINH,
	COUNT(dbo.PHANCONG.MADUAN) AS SoDuAn
FROM
	dbo.NHANVIEN,
	dbo.PHANCONG
WHERE
	dbo.NHANVIEN.MANV = dbo.PHANCONG.MANV
GROUP BY
	dbo.NHANVIEN.MANV,
	dbo.NHANVIEN.HOTENNV,
	dbo.NHANVIEN.GIOITINH
HAVING
	COUNT(dbo.PHANCONG.MADUAN) >= 2